## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/images/*"
  to = "https://res.cloudinary.com/okikio-assets/image/:splat"
  status = 200
  headers = {X-From = "Netlify", X-Robots-Tag = "none, noimageindex, noarchive", Cache-Control = "public, max-age=604800, must-revalidate"}